name: MLflow Project CI - Retrain Heart Disease Model

on:
  push:
    branches:
      - main # Or your default branch, e.g., master
    paths:
      - 'MLProject_Heart/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  retrain-and-log-model:
    runs-on: ubuntu-latest
    # REMOVE or COMMENT OUT the default working-directory here for now,
    # OR be very careful with relative paths in each step.
    # Let's remove it for now and use explicit paths where needed.
    # defaults:
    #   run:
    #     working-directory: ./MLProject_Heart

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.10'
          # Provide the path to conda.yaml relative to the repository root
          environment-file: MLProject_Heart/conda.yaml # <--- CORRECTED PATH
          activate-environment: heart_disease_ci_env
          use-only-tar-bz2: true

      - name: Run MLflow Project for Model Retraining
        # Now, explicitly set the working directory for this step OR
        # run mlflow with a path to the project
        working-directory: ./MLProject_Heart # Set working directory for this specific step
        shell: bash -el {0}
        run: |
          # Now that we are in MLProject_Heart, 'mlflow run .' should work
          mlflow run . --experiment-name "CI_Heart_Disease_Retraining_Experiment"
          echo "MLflow run completed."

      - name: Upload MLflow Run Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-run-ci-artifacts
          # Path is relative to repository root if working-directory is not set for this step globally
          # OR it's relative to the working-directory if set for the step.
          # Since `mlruns` is created inside `MLProject_Heart` when `mlflow run .` is executed there:
          path: MLProject_Heart/mlruns # <--- Path relative to GITHUB_WORKSPACE
          retention-days: 7